# Generated by Django 4.0.4 on 2022-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='department-backgrounds/'),
        ),
    ]
