# Generated by Django 4.0.4 on 2022-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_department_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='developers-icons/'),
        ),
    ]
