# Generated by Django 4.0.4 on 2022-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_developers_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='location',
            field=models.CharField(blank=True, help_text='Developer Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='name',
            field=models.CharField(blank=True, help_text='Developer Name', max_length=255, null=True),
        ),
    ]
