# Generated by Django 4.0.4 on 2022-05-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_developers_location_alter_developers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='states.department'),
        ),
    ]
