# Generated by Django 4.0.4 on 2022-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_projects_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='background_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photos/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='background_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photos/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='background_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photos/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='projects-photos/'),
        ),
    ]
