# Generated by Django 4.0.4 on 2022-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_projects_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
